version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16.10.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
      - run: |
              TESTFILES=$(circleci tests glob "test/**/*.test.js" | circleci tests split --split-by=timings)
              CI=true npm run test $TESTFILES

workflows:
  test:
    jobs:
      - test