version: 2.1

jobs:
  test:
    parameters:
      calculation:
        type: boolean
        default: false
    docker:
      - image: circleci/node:16.10.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: |
              TESTFILES=$(circleci tests glob "*.test.js" | circleci tests split)
              CI=true npm run test $TESTFILES
      - store_artifacts:
          path: test_report.json
      - when:
          condition: << parameters.calculation >>
          steps:
            - run: npm run start

workflows:
  test:
    jobs:
      - test:
          calculation: false
          name: [test-ci]
      - test:
          calculation: true
          requires: [test-ci]