version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.10.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circle/node:16.10.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    parallelism: 2
    steps:
      - checkout
      - run: npm test
      - run:
          command: |
            echo $(circleci tests glob "*.test.js" | circleci tests split --split-by=timings)

workflows:
  build_and_test:
    jobs:
      - build
      - test